// Regenerate fonts.css: fetch the exact webfont CSS the app uses (Satoshi via
// Fontshare, Instrument Sans + JetBrains Mono via Google Fonts), download the
// referenced woff2 files, and inline them as base64 data: URIs into a single
// self-contained stylesheet. The render function injects this instead of loading
// fonts over the network, so the headless-Chrome screenshot doesn't wait on font
// downloads (the slow part of cold renders). Latin subsets only (English tracker).
//
// Run: node api/_lib/fonts/build.mjs   (writes api/_lib/fonts/fonts.css)

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

const GOOGLE_CSS =
  'https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap'
const FONTSHARE_CSS = 'https://api.fontshare.com/v2/css?f[]=satoshi@400,500,600,700&display=swap'

async function fetchText(url) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!r.ok) throw new Error(`fetch ${url} -> ${r.status}`)
  return await r.text()
}

async function woff2DataUri(url) {
  const abs = url.startsWith('//') ? `https:${url}` : url
  const r = await fetch(abs, { headers: { 'User-Agent': UA } })
  if (!r.ok) throw new Error(`fetch font ${abs} -> ${r.status}`)
  const buf = Buffer.from(await r.arrayBuffer())
  return `data:font/woff2;base64,${buf.toString('base64')}`
}

// Replace the first woff2 url(...) in a src: line with a data URI; drop woff/ttf fallbacks.
async function inlineFontFace(block) {
  const m = block.match(/url\(\s*['"]?([^'")]+\.woff2[^'")]*)['"]?\s*\)/i)
  if (!m) return null
  const dataUri = await woff2DataUri(m[1])
  // Rewrite src to a single woff2 data URI.
  return block.replace(/src:\s*[^;]+;/, `src: url(${dataUri}) format('woff2');`)
}

async function processGoogle(css) {
  // Keep only latin / latin-ext subsets.
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g
  const out = []
  let mt
  while ((mt = re.exec(css)) !== null) {
    const subset = mt[1]
    if (subset !== 'latin' && subset !== 'latin-ext') continue
    const inlined = await inlineFontFace(mt[2])
    if (inlined) out.push(`/* ${subset} */\n${inlined}`)
  }
  return out.join('\n')
}

async function processFontshare(css) {
  const re = /@font-face\s*\{[^}]*\}/g
  const out = []
  let mt
  while ((mt = re.exec(css)) !== null) {
    const inlined = await inlineFontFace(mt[0])
    if (inlined) out.push(inlined)
  }
  return out.join('\n')
}

const [gcss, fcss] = await Promise.all([fetchText(GOOGLE_CSS), fetchText(FONTSHARE_CSS)])
const google = await processGoogle(gcss)
const fontshare = await processFontshare(fcss)

const header =
  '/* GENERATED by api/_lib/fonts/build.mjs — do not edit by hand.\n' +
  '   Self-hosted webfonts (base64) so the preview render does not wait on font\n' +
  '   downloads. Mirrors the app fonts: Satoshi, Instrument Sans, JetBrains Mono. */\n'

fs.writeFileSync(path.join(__dirname, 'fonts.css'), `${header}\n${fontshare}\n${google}\n`)
console.log('wrote fonts.css')
